//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Food_Pasada.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cbh_order
    {
        public int id { get; set; }
        public string f_name { get; set; }
        public string address { get; set; }
        public string number { get; set; }
        public string product { get; set; }
        public string price { get; set; }
        public string image { get; set; }
        public string email { get; set; }
    }
}
