//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Food_Pasada.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class food_pasadaEntities : DbContext
    {
        public food_pasadaEntities()
            : base("name=food_pasadaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cbh_order> cbh_order { get; set; }
        public virtual DbSet<cbh_product> cbh_product { get; set; }
        public virtual DbSet<fp_admin> fp_admin { get; set; }
        public virtual DbSet<gnb_order> gnb_order { get; set; }
        public virtual DbSet<gnb_product> gnb_product { get; set; }
        public virtual DbSet<qt_order> qt_order { get; set; }
        public virtual DbSet<qt_product> qt_product { get; set; }
        public virtual DbSet<res_admin> res_admin { get; set; }
        public virtual DbSet<tbl_msg> tbl_msg { get; set; }
        public virtual DbSet<tbl_riders> tbl_riders { get; set; }
    }
}
