//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Food_Pasada.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class res_admin
    {
        public int id { get; set; }
        public string f_name { get; set; }
        public string address { get; set; }
        public string rest_name { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
    }
}
